services:
  database:
    image: mysql:8.0
    restart: always
    container_name: mysql
    healthcheck:
      test: ["CMD", 'root', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 20s
      retries: 10
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - "54132:3306"
    # 환경 변수 설정
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: wanted
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  backend:
    env_file:
      - .env
    container_name: wanted
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    # mysql 컨테이너가 사용 가능한 시점에 backend 컨테이너 시작
    depends_on:
      database:
        condition: service_completed_successfully

# 백엔드 API에만 접근한다면 nginx(리버스 프록시) 등은 필수는 아니라고 생각해 추가하지 않았습니다.