services:
  database:
    image: mysql:8.0
    restart: always
    container_name: mysql
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - "54132:3306"
    # 환경 변수 설정
    environment:
      MYSQL_DATABASE: wanted
      MYSQL_USER: hanjunsoo
      MYSQL_PASSWORD: hanjunsooPassword
      MYSQL_ROOT_PASSWORD: hanjunsooRootPassword
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data/mysql/:/var/lib/mysql
  backend:
    container_name: wanted
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database