services:
  database:
    image: mysql:8.0
    restart: always
    container_name: mysql
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - "54132:3306"
    # 환경 변수 설정
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: wanted
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  backend:
    env_file:
      - .env
    container_name: wanted
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database