server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://${DATABASE_URL}?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: hanjunoo
    password: hanjunsooPassword
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      default_batch_fetch_size: 100
    open-in-view: false

logging:
  level:
    '[com.wanted.preonboarding]': INFO
    '[org.hibernate.type]': TRACE